// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plannoy.Persistance;

namespace Persistance.Migrations
{
    [DbContext(typeof(PlannoyDbContext))]
    [Migration("20200221015209_TransactionTable")]
    partial class TransactionTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("Plannoy.Domain.Establishment", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Establishment");
                });

            modelBuilder.Entity("Plannoy.Domain.Transaction", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("EstablishmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReferenceDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EstablishmentId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("Plannoy.Domain.Transaction", b =>
                {
                    b.HasOne("Plannoy.Domain.Establishment", "Establishment")
                        .WithMany("Transactions")
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Plannoy.Domain.Money", "Money", b1 =>
                        {
                            b1.Property<long>("TransactionId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Currency")
                                .HasColumnName("MoneyCurrency")
                                .HasColumnType("INTEGER")
                                .HasMaxLength(3);

                            b1.Property<decimal>("Value")
                                .HasColumnName("MoneyValue")
                                .HasColumnType("TEXT");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transaction");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
